on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build
        run: |
          go mod vendor
          go build -ldflags "-s -w" -v -o ws-proxy

      - name: Compress
        run: tar czvf ws-proxy.tar.gz ws-proxy

      - name: release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ws-proxy.tar.gz
          asset_name: ws-proxy-$tag-${{ matrix.os }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: ws-proxy release ${{ env.RELEASE_VERSION }}
